# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-25 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0069_auto_20210128_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='parkstay.Feature'),
        ),
    ]
